from __future__ import annotations

"""
backend/ml_context_recommender.py

Purpose (defense-friendly):
- Centralize the full "Context + ML" ranking logic in one reusable module.
- Let advanced NLP context change the RANKING itself, not just the explanation text.
- Keep the logic transparent enough to defend to instructors / committee.
- Add strict guardrails so missing/ambiguous NLP outputs do NOT send garbage data
  into the ranking logic.

Important design choices:
1) This module does NOT import spaCy or NLTK directly.
   It only consumes already-parsed context, which keeps memory overhead low in
   the ranking path and avoids extra model loads during requests.
2) If parsing fails or is incomplete, this module falls back to safe neutral
   defaults:
      - margin = 0.0
      - period = 4
      - time_remaining = 360.0
   Those defaults intentionally avoid extreme late-game bias.
3) RATIONALE is generated by a deterministic template only.
   No language model is used here, so there is no hallucination risk in the
   coaching explanation text produced by this module.
4) A small built-in validation helper is included so the project can
   programmatically verify core mappings like:
      - "down 5" -> -5
      - "leading by 3" -> 3
      - "Q4" -> 4
      - "0:28" -> 28
"""

from pathlib import Path
import re
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd

from domain.baseline_recommendation import BaselineRecommender

try:
    from infrastructure.external_integrations.nlp_reasoning import infer_play_family_from_name
except Exception:  # pragma: no cover

        def infer_play_family_from_name(play_name: str) -> Optional[str]:
            name = (play_name or "").strip().lower().replace("_", " ").replace("-", " ")
            if not name:
                return None
            alias_map = {
                "ball_screen": ["pick", "pnr", "ball screen", "drag", "ghost", "slip"],
                "handoff": ["handoff", "hand off", "dho", "zoom", "pistol"],
                "post_up": ["post", "duck in", "seal"],
                "isolation": ["iso", "isolation", "clear out"],
                "spot_up": ["spot up", "catch and shoot", "kick out", "corner three"],
                "off_screen": ["off screen", "stagger", "flare", "pin down", "elevator", "hammer"],
                "cut": ["cut", "back cut", "45 cut", "dive"],
                "transition": ["transition", "early offense", "hit ahead", "run out", "push"],
            }
            for family, aliases in alias_map.items():
                for alias in aliases:
                    if alias in name:
                        return family
            return None


# ---------------------------------------------------------------------
# Data paths / caches
# ---------------------------------------------------------------------

DATA_DIR = Path(__file__).resolve().parent.parent.parent / "data"
SYNERGY_CSV_PATH = DATA_DIR / "synergy_playtypes_2019_2025_players.csv"
ML_PRED_PATH = DATA_DIR / "ml_offense_ppp_predictions.csv"

_rec = BaselineRecommender(str(SYNERGY_CSV_PATH))
_ML_PRED_DF: Optional[pd.DataFrame] = None

MODULE_VERSION = "3.0.0"
RATIONALE_MODE = "template"

# Safe neutral fallbacks used when NLP parsing is missing/ambiguous.
DEFAULT_MARGIN = 0.0
DEFAULT_PERIOD = 4
DEFAULT_TIME_REMAINING = 360.0  # 6:00 in Q4 -> neutral, non-extreme context

# ---------------------------------------------------------------------
# Family mappings (transparent + easy to defend)
# ---------------------------------------------------------------------

FAMILIES: Tuple[str, ...] = (
    "ball_screen",
    "handoff",
    "post_up",
    "isolation",
    "spot_up",
    "off_screen",
    "cut",
    "transition",
    "other",
)

QUICK_WEIGHTS: Dict[str, float] = {
    "Spotup": 1.00,
    "OffScreen": 0.80,
    "Cut": 0.60,
    "Isolation": 0.40,
    "P&R Ball Handler": 0.55,
    "P&R Roll Man": 0.60,
    "Handoff": 0.65,
}

FAMILY_QUICK_WEIGHTS: Dict[str, float] = {
    "spot_up": 1.00,
    "off_screen": 0.85,
    "cut": 0.75,
    "handoff": 0.70,
    "transition": 0.70,
    "ball_screen": 0.60,
    "isolation": 0.45,
    "post_up": 0.30,
    "other": 0.0,
}

NEED_FAMILY_BONUS: Dict[str, Dict[str, float]] = {
    "need3": {
        "spot_up": 0.055,
        "off_screen": 0.050,
        "handoff": 0.032,
        "ball_screen": 0.022,
        "transition": 0.015,
    },
    "quick2": {
        "cut": 0.055,
        "ball_screen": 0.045,
        "handoff": 0.035,
        "transition": 0.025,
        "post_up": 0.018,
    },
    "two_for_one": {
        "spot_up": 0.040,
        "off_screen": 0.036,
        "handoff": 0.028,
        "transition": 0.024,
        "ball_screen": 0.016,
    },
    "last_shot": {
        "isolation": 0.040,
        "ball_screen": 0.030,
        "post_up": 0.024,
        "handoff": 0.018,
    },
    "must_score": {
        "ball_screen": 0.036,
        "handoff": 0.028,
        "off_screen": 0.022,
        "post_up": 0.020,
        "isolation": 0.015,
    },
    "safe": {
        "post_up": 0.020,
        "ball_screen": 0.016,
        "handoff": 0.012,
    },
}

DEFENSE_STYLE_FAMILY_BONUS: Dict[str, Dict[str, float]] = {
    "switch": {
        "cut": 0.034,
        "post_up": 0.028,
        "ball_screen": 0.012,
        "off_screen": 0.016,
        "handoff": 0.012,
    },
    "drop": {
        "ball_screen": 0.045,
        "handoff": 0.026,
        "spot_up": 0.020,
        "off_screen": 0.015,
    },
    "hedge": {
        "cut": 0.032,
        "handoff": 0.020,
        "ball_screen": 0.016,
        "spot_up": 0.014,
    },
    "blitz": {
        "cut": 0.035,
        "handoff": 0.020,
        "spot_up": 0.016,
        "ball_screen": 0.015,
    },
    "ice": {
        "handoff": 0.024,
        "ball_screen": 0.020,
        "cut": 0.018,
    },
    "under": {
        "ball_screen": 0.032,
        "handoff": 0.020,
        "spot_up": 0.016,
    },
    "top_lock": {
        "cut": 0.032,
        "handoff": 0.016,
        "off_screen": 0.012,
    },
    "zone_2_3": {
        "off_screen": 0.042,
        "spot_up": 0.038,
        "post_up": 0.026,
        "cut": 0.020,
        "handoff": 0.016,
    },
    "zone_3_2": {
        "off_screen": 0.040,
        "spot_up": 0.036,
        "post_up": 0.022,
        "cut": 0.018,
        "handoff": 0.014,
    },
    "zone_1_3_1": {
        "off_screen": 0.038,
        "spot_up": 0.036,
        "cut": 0.024,
        "handoff": 0.016,
    },
    "box_and_1": {
        "post_up": 0.030,
        "off_screen": 0.022,
        "cut": 0.020,
        "spot_up": 0.015,
    },
    "matchup_zone": {
        "off_screen": 0.038,
        "spot_up": 0.032,
        "cut": 0.020,
        "handoff": 0.015,
    },
    "generic_zone": {
        "off_screen": 0.034,
        "spot_up": 0.030,
        "cut": 0.018,
        "post_up": 0.018,
    },
}

PACE_FAMILY_BONUS: Dict[str, Dict[str, float]] = {
    "push": {
        "transition": 0.050,
        "cut": 0.030,
        "spot_up": 0.018,
        "ball_screen": 0.010,
    },
    "slow": {
        "post_up": 0.024,
        "ball_screen": 0.016,
        "isolation": 0.016,
        "off_screen": 0.010,
    },
}

SPECIAL_FAMILY_BONUS: Dict[str, Dict[str, float]] = {
    "after_timeout": {
        "off_screen": 0.036,
        "handoff": 0.026,
        "post_up": 0.020,
        "ball_screen": 0.020,
        "spot_up": 0.016,
    },
    "slob": {
        "off_screen": 0.042,
        "spot_up": 0.032,
        "cut": 0.026,
        "handoff": 0.020,
    },
    "blob": {
        "cut": 0.042,
        "off_screen": 0.036,
        "post_up": 0.030,
        "spot_up": 0.024,
    },
    "advance_ball": {
        "spot_up": 0.036,
        "off_screen": 0.030,
        "handoff": 0.020,
    },
}

LATE_CLOCK_FAMILY_BONUS: Dict[str, float] = {
    "ball_screen": 0.028,
    "handoff": 0.022,
    "isolation": 0.020,
    "spot_up": 0.015,
    "cut": 0.014,
    "off_screen": 0.012,
    "post_up": 0.010,
    "transition": -0.010,
    "other": 0.0,
}

RISKY_FAMILIES: Tuple[str, ...] = ("transition", "isolation")
SECURE_FAMILIES: Tuple[str, ...] = ("post_up", "ball_screen", "handoff")

# ---------------------------------------------------------------------
# Parsing guardrails / validation helpers
# ---------------------------------------------------------------------

_WORD_NUMBERS = {
    "zero": 0,
    "one": 1,
    "two": 2,
    "three": 3,
    "four": 4,
    "five": 5,
    "six": 6,
    "seven": 7,
    "eight": 8,
    "nine": 9,
    "ten": 10,
}

_MARGIN_DOWN_RE = re.compile(
    r"\b(?:down|trailing|behind)\s*(?:by\s*)?(?P<n>\d{1,2}|one|two|three|four|five|six|seven|eight|nine|ten)\b",
    flags=re.IGNORECASE,
)
_MARGIN_UP_RE = re.compile(
    r"\b(?:up|leading|ahead)\s*(?:by\s*)?(?P<n>\d{1,2}|one|two|three|four|five|six|seven|eight|nine|ten)\b",
    flags=re.IGNORECASE,
)
_MARGIN_TIED_RE = re.compile(r"\b(?:tie|tied|even)\b", flags=re.IGNORECASE)

_PERIOD_PATTERNS: Tuple[Tuple[int, re.Pattern[str]], ...] = (
    (5, re.compile(r"\b(?:ot|overtime)\b", flags=re.IGNORECASE)),
    (4, re.compile(r"\b(?:q\s*4|4th\s*(?:q|quarter)|fourth\s+quarter)\b", flags=re.IGNORECASE)),
    (3, re.compile(r"\b(?:q\s*3|3rd\s*(?:q|quarter)|third\s+quarter)\b", flags=re.IGNORECASE)),
    (2, re.compile(r"\b(?:q\s*2|2nd\s*(?:q|quarter)|second\s+quarter)\b", flags=re.IGNORECASE)),
    (1, re.compile(r"\b(?:q\s*1|1st\s*(?:q|quarter)|first\s+quarter)\b", flags=re.IGNORECASE)),
)

_TIME_MMSS_RE = re.compile(r"\b(?P<mm>\d{1,2})\s*:\s*(?P<ss>\d{2})\b")
_TIME_SECONDS_RE = re.compile(r"\b(?P<s>\d{1,3})\s*(?:s|sec|secs|second|seconds)\b", flags=re.IGNORECASE)
_TIME_MINUTES_RE = re.compile(r"\b(?P<m>\d{1,2})\s*(?:m|min|mins|minute|minutes)\b", flags=re.IGNORECASE)


# ---------------------------------------------------------------------
# Small helpers
# ---------------------------------------------------------------------

def _clamp(x: float, lo: float, hi: float) -> float:
    return float(max(lo, min(hi, x)))


def _safe_float(x: Any) -> Optional[float]:
    try:
        v = float(x)
        if np.isnan(v) or np.isinf(v):
            return None
        return float(v)
    except Exception:
        return None


def _safe_str(x: Any) -> Optional[str]:
    if isinstance(x, str):
        s = x.strip()
        return s if s else None
    return None


def _as_list_str(x: Any) -> List[str]:
    if isinstance(x, list):
        out: List[str] = []
        seen = set()
        for item in x:
            if isinstance(item, str):
                val = item.strip()
                if val and val not in seen:
                    out.append(val)
                    seen.add(val)
        return out
    return []


def _truthy(x: Any) -> bool:
    if isinstance(x, bool):
        return x
    if isinstance(x, (int, float)):
        return bool(x)
    if isinstance(x, str):
        return x.strip().lower() in {"1", "true", "yes", "y", "on"}
    return False


def _num_from_token(token: Any) -> Optional[int]:
    if token is None:
        return None
    t = str(token).strip().lower()
    if not t:
        return None
    if t.isdigit():
        return int(t)
    return _WORD_NUMBERS.get(t)


def _dedupe_keep_order(values: Sequence[str]) -> List[str]:
    out: List[str] = []
    seen = set()
    for value in values:
        if not isinstance(value, str):
            continue
        s = value.strip()
        if not s or s in seen:
            continue
        out.append(s)
        seen.add(s)
    return out


def _get_ml_pred_df() -> pd.DataFrame:
    global _ML_PRED_DF
    if _ML_PRED_DF is None:
        if not ML_PRED_PATH.exists():
            raise FileNotFoundError(f"Missing ML prediction file: {ML_PRED_PATH}")
        _ML_PRED_DF = pd.read_csv(ML_PRED_PATH)

        required_cols = {"SEASON", "TEAM_ABBREVIATION", "PLAY_TYPE", "PPP_ML"}
        missing = required_cols.difference(set(_ML_PRED_DF.columns))
        if missing:
            raise ValueError(
                "ml_offense_ppp_predictions.csv is missing required columns: "
                + ", ".join(sorted(missing))
            )

    return _ML_PRED_DF.copy()


def total_time_remaining(period: int, time_remaining_period_sec: float) -> float:
    """
    Total seconds remaining in regulation (4x12). OT is treated as 0 remaining.
    """
    if period >= 5:
        return 0.0
    total_reg = 4 * 12 * 60
    elapsed = (period - 1) * 12 * 60 + (12 * 60 - time_remaining_period_sec)
    return float(max(0.0, total_reg - elapsed))


def compute_context_factors(
    margin: float,
    period: int,
    time_remaining_period_sec: float,
) -> Tuple[float, float, float]:
    """
    The 3 legacy factors your current app already uses.
    """
    t_left = total_time_remaining(period, time_remaining_period_sec)

    late_window = 180.0
    late_game_factor = _clamp((late_window - t_left) / late_window, 0.0, 1.0)

    trailing_factor = _clamp((-margin) / 10.0, 0.0, 1.0) if margin < 0 else 0.0
    leading_factor = _clamp((margin) / 10.0, 0.0, 1.0) if margin > 0 else 0.0

    return float(late_game_factor), float(trailing_factor), float(leading_factor)


def label_context(late_game_factor: float, trailing_factor: float, leading_factor: float) -> str:
    if late_game_factor >= 0.5 and trailing_factor > 0:
        return "Late & trailing"
    if late_game_factor >= 0.5 and leading_factor > 0:
        return "Late & leading"
    return "Normal context"


def _play_family(play_type: Any) -> str:
    family = infer_play_family_from_name(str(play_type or ""))
    return family if family in FAMILIES else "other"


def _lookup_nested(mapping: Dict[str, Dict[str, float]], outer_key: Optional[str], family: str) -> float:
    if not outer_key:
        return 0.0
    family_map = mapping.get(outer_key, {})
    return float(family_map.get(family, 0.0))


def _lookup_family_bonus(mapping: Dict[str, float], family: str) -> float:
    return float(mapping.get(family, 0.0))


def _preferred_family_bonus(preferred: Sequence[str], family: str) -> float:
    if not preferred:
        return 0.0
    if family in preferred:
        return 0.040
    return 0.0


def _fallback_biases_from_context(context: Dict[str, Any]) -> Tuple[Optional[float], Optional[float]]:
    """
    Use parser-provided offense_bias/defense_bias when available.
    Otherwise infer a conservative fallback from the parsed need flags.
    """
    off = _safe_float(context.get("offense_bias"))
    deff = _safe_float(context.get("defense_bias"))
    if off is not None and deff is not None and abs((off + deff) - 1.0) <= 0.25:
        return _clamp(off, 0.0, 1.0), _clamp(deff, 0.0, 1.0)

    needs = set(_as_list_str(context.get("needs")))
    need = _safe_str(context.get("need"))
    if need:
        needs.add(need)

    if "stop" in needs or _truthy(context.get("must_stop")) or _truthy(context.get("no_three")):
        return 0.20, 0.80
    if (
        "need3" in needs
        or "quick2" in needs
        or "two_for_one" in needs
        or "must_score" in needs
        or _truthy(context.get("need3"))
        or _truthy(context.get("quick2"))
        or _truthy(context.get("two_for_one"))
        or _truthy(context.get("must_score"))
    ):
        return 0.75, 0.25
    if "safe" in needs or _truthy(context.get("safe")) or _truthy(context.get("protect_lead")):
        return 0.42, 0.58

    return None, None


def _resolve_effective_weights(
    context: Optional[Dict[str, Any]],
    w_off: float,
    w_def: float,
) -> Tuple[float, float]:
    """
    Let advanced NLP context change how much the ranking trusts our offense
    versus opponent defense. This is a meaningful ranking change, not just text.
    """
    base_w_off = float(w_off)
    ctx = context or {}
    ctx_w_off, _ctx_w_def = _fallback_biases_from_context(ctx)

    if ctx_w_off is None:
        eff_w_off = _clamp(base_w_off, 0.10, 0.90)
        return eff_w_off, float(1.0 - eff_w_off)

    eff_w_off = _clamp(0.35 * base_w_off + 0.65 * ctx_w_off, 0.10, 0.90)
    eff_w_def = float(1.0 - eff_w_off)
    return eff_w_off, eff_w_def


# ---------------------------------------------------------------------
# Context guardrails / safe parsing
# ---------------------------------------------------------------------

def _parse_margin_hint(value: Any) -> Optional[float]:
    if value is None:
        return None
    text = str(value).strip().lower()
    if not text:
        return None

    if _MARGIN_TIED_RE.search(text):
        return 0.0

    m = _MARGIN_DOWN_RE.search(text)
    if m:
        n = _num_from_token(m.group("n"))
        if n is not None:
            return float(-abs(n))

    m = _MARGIN_UP_RE.search(text)
    if m:
        n = _num_from_token(m.group("n"))
        if n is not None:
            return float(abs(n))

    return None


def _parse_period_hint(value: Any) -> Optional[int]:
    if value is None:
        return None

    numeric = _safe_float(value)
    if numeric is not None:
        period = int(round(float(numeric)))
        if 1 <= period <= 5:
            return period

    text = str(value).strip().lower()
    if not text:
        return None

    for parsed_period, pattern in _PERIOD_PATTERNS:
        if pattern.search(text):
            return parsed_period

    return None


def _parse_time_hint(value: Any) -> Optional[float]:
    if value is None:
        return None

    numeric = _safe_float(value)
    if numeric is not None and 0.0 <= float(numeric) <= 720.0:
        return float(numeric)

    text = str(value).strip().lower()
    if not text:
        return None

    m = _TIME_MMSS_RE.search(text)
    if m:
        mm = int(m.group("mm"))
        ss = int(m.group("ss"))
        if 0 <= ss < 60:
            return float(mm * 60 + ss)

    m = _TIME_SECONDS_RE.search(text)
    if m:
        return float(int(m.group("s")))

    m = _TIME_MINUTES_RE.search(text)
    if m:
        return float(int(m.group("m")) * 60)

    return None


def validate_context_guardrails() -> Dict[str, Any]:
    """
    Small programmatic validation helper for core context mappings.
    This does not replace a real test suite, but it gives the project a
    deterministic self-check for the most important parsing guardrails.
    """
    checks = [
        ("margin_down_5", _parse_margin_hint("down 5"), -5.0),
        ("margin_leading_3", _parse_margin_hint("leading by 3"), 3.0),
        ("margin_tied", _parse_margin_hint("tie game"), 0.0),
        ("period_q4", _parse_period_hint("Q4"), 4),
        ("period_ot", _parse_period_hint("overtime"), 5),
        ("clock_mmss", _parse_time_hint("0:28"), 28.0),
        ("clock_seconds", _parse_time_hint("28 seconds"), 28.0),
        ("clock_minutes", _parse_time_hint("2 minutes"), 120.0),
    ]

    details: List[Dict[str, Any]] = []
    passed = 0

    for name, actual, expected in checks:
        ok = actual == expected
        if ok:
            passed += 1
        details.append(
            {
                "name": name,
                "actual": actual,
                "expected": expected,
                "ok": ok,
            }
        )

    return {
        "status": "ok" if passed == len(checks) else "failed",
        "passed": passed,
        "total": len(checks),
        "details": details,
        "module_version": MODULE_VERSION,
    }


def recommender_health() -> Dict[str, Any]:
    """
    Lightweight environment/runtime health check.

    This is useful for showing that the recommender path itself is lightweight
    and does not load spaCy/NLTK models during ranking.
    """
    ml_file_exists = ML_PRED_PATH.exists()
    synergy_file_exists = SYNERGY_CSV_PATH.exists()

    return {
        "status": "ok" if ml_file_exists and synergy_file_exists else "degraded",
        "module_version": MODULE_VERSION,
        "spacy_loaded_here": False,
        "nltk_loaded_here": False,
        "ml_predictions_file_exists": ml_file_exists,
        "synergy_file_exists": synergy_file_exists,
        "rationale_mode": RATIONALE_MODE,
        "fallback_defaults": {
            "margin": DEFAULT_MARGIN,
            "period": DEFAULT_PERIOD,
            "time_remaining": DEFAULT_TIME_REMAINING,
        },
    }


def _sanitize_numeric_context(
    raw_margin: Any,
    raw_period: Any,
    raw_time_remaining: Any,
) -> Tuple[float, int, float, List[str], List[str]]:
    """
    Returns:
      margin, period, time_remaining, defaults_used, guardrails
    """
    defaults_used: List[str] = []
    guardrails: List[str] = []

    # -------------------------
    # margin
    # -------------------------
    margin = _safe_float(raw_margin)
    if margin is None:
        margin = _parse_margin_hint(raw_margin)

    if margin is None:
        margin = DEFAULT_MARGIN
        defaults_used.append("margin")
        guardrails.append("margin defaulted to 0.0 because no reliable score margin was parsed.")
    else:
        if float(margin) < -50.0 or float(margin) > 50.0:
            guardrails.append(f"margin {margin} was out of range and clamped into [-50, 50].")
        margin = float(_clamp(float(margin), -50.0, 50.0))

    # -------------------------
    # period
    # -------------------------
    period = _parse_period_hint(raw_period)
    if period is None:
        period = DEFAULT_PERIOD
        defaults_used.append("period")
        guardrails.append("period defaulted to 4 because no reliable quarter/period was parsed.")

    # -------------------------
    # time remaining
    # -------------------------
    time_remaining = _parse_time_hint(raw_time_remaining)
    if time_remaining is None:
        time_remaining = DEFAULT_TIME_REMAINING
        defaults_used.append("time_remaining")
        guardrails.append("time_remaining defaulted to 360.0 seconds because no reliable clock value was parsed.")
    else:
        if float(time_remaining) < 0.0 or float(time_remaining) > 720.0:
            guardrails.append(f"time_remaining {time_remaining} was out of range and clamped into [0, 720].")
        time_remaining = float(_clamp(float(time_remaining), 0.0, 720.0))

    return float(margin), int(period), float(time_remaining), defaults_used, guardrails


def _normalize_context(
    margin: Any,
    period: Any,
    time_remaining_period_sec: Any,
    context: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """
    Central guardrail boundary for all recommender ranking inputs.

    If the parser gives clean values, they are preserved.
    If the parser gives nothing / invalid values, the recommender falls back to:
      margin=0.0, period=4, time_remaining=360.0
    and records exactly what happened in guardrail metadata.
    """
    raw = context.copy() if isinstance(context, dict) else {}

    # Prefer explicit parser/context values, then function args.
    raw_margin = raw.get("margin", margin)
    raw_period = raw.get("period", period)
    raw_time_remaining = raw.get("time_remaining", time_remaining_period_sec)

    safe_margin, safe_period, safe_time_remaining, defaults_used, guardrails = _sanitize_numeric_context(
        raw_margin=raw_margin,
        raw_period=raw_period,
        raw_time_remaining=raw_time_remaining,
    )

    out: Dict[str, Any] = {
        "margin": safe_margin,
        "period": safe_period,
        "time_remaining": safe_time_remaining,
        "shot_clock": None,
        "need": _safe_str(raw.get("need")),
        "needs": _as_list_str(raw.get("needs")),
        "defense_style": _safe_str(raw.get("defense_style")),
        "pace": _safe_str(raw.get("pace")),
        "preferred_play_families": _as_list_str(raw.get("preferred_play_families")),
        "special_situations": _as_list_str(raw.get("special_situations")),
        "_defaults_used": defaults_used,
        "_guardrails": guardrails,
        "_parse_status": "defaulted" if defaults_used else "parsed",
        "_validation_ok": len(defaults_used) == 0,
    }

    shot_clock = _safe_float(raw.get("shot_clock"))
    if shot_clock is not None:
        out["shot_clock"] = _clamp(float(shot_clock), 0.0, 24.0)

    bool_keys = [
        "after_timeout",
        "slob",
        "blob",
        "advance_ball",
        "late_clock",
        "need3",
        "protect_lead",
        "end_of_quarter",
        "vs_switching",
        "must_stop",
        "quick2",
        "two_for_one",
        "hold_for_last",
        "foul_game",
        "no_three",
        "must_score",
        "safe",
    ]
    for key in bool_keys:
        out[key] = _truthy(raw.get(key))

    if out["need"] and out["need"] not in out["needs"]:
        out["needs"].append(out["need"])

    if out["after_timeout"] and "after_timeout" not in out["special_situations"]:
        out["special_situations"].append("after_timeout")
    if out["slob"] and "slob" not in out["special_situations"]:
        out["special_situations"].append("slob")
    if out["blob"] and "blob" not in out["special_situations"]:
        out["special_situations"].append("blob")
    if out["advance_ball"] and "advance_ball" not in out["special_situations"]:
        out["special_situations"].append("advance_ball")

    if out["need3"] and "need3" not in out["needs"]:
        out["needs"].append("need3")
    if out["quick2"] and "quick2" not in out["needs"]:
        out["needs"].append("quick2")
    if out["two_for_one"] and "two_for_one" not in out["needs"]:
        out["needs"].append("two_for_one")
    if out["hold_for_last"] and "last_shot" not in out["needs"]:
        out["needs"].append("last_shot")
    if out["must_score"] and "must_score" not in out["needs"]:
        out["needs"].append("must_score")
    if out["safe"] and "safe" not in out["needs"]:
        out["needs"].append("safe")

    if out["defense_style"] == "switch":
        out["vs_switching"] = True

    out["needs"] = _dedupe_keep_order(out["needs"])
    out["special_situations"] = _dedupe_keep_order(out["special_situations"])
    out["preferred_play_families"] = _dedupe_keep_order(out["preferred_play_families"])

    if _safe_str(raw.get("parser_version")):
        out["parser_version"] = str(raw["parser_version"]).strip()
    if _safe_str(raw.get("nlp_pipeline_version")):
        out["nlp_pipeline_version"] = str(raw["nlp_pipeline_version"]).strip()

    return out


def sanitize_context_for_ranking(
    context: Optional[Dict[str, Any]] = None,
    *,
    margin: Any = None,
    period: Any = None,
    time_remaining: Any = None,
) -> Dict[str, Any]:
    """
    Public helper so endpoint code can sanitize/normalize NLP context before
    it reaches ranking logic.

    This is the explicit integration boundary for:
    - fallback defaults
    - clamping
    - bool/special-situation normalization
    - audit metadata about what had to be defaulted
    """
    return _normalize_context(
        margin=margin,
        period=period,
        time_remaining_period_sec=time_remaining,
        context=context,
    )


def _context_priority_multiplier(
    ctx: Dict[str, Any],
    late_game_factor: float,
    trailing_factor: float,
    leading_factor: float,
) -> float:
    mult = 1.0
    if ctx["need"] in {"need3", "quick2", "two_for_one", "must_score"}:
        mult += 0.25 * late_game_factor
        mult += 0.20 * trailing_factor
    if ctx["need"] in {"safe"} or ctx["protect_lead"]:
        mult += 0.18 * leading_factor
    if ctx["after_timeout"] or ctx["slob"] or ctx["blob"]:
        mult += 0.08
    return float(mult)


def _make_context_label(
    ctx: Dict[str, Any],
    late_game_factor: float,
    trailing_factor: float,
    leading_factor: float,
) -> str:
    parts: List[str] = [label_context(late_game_factor, trailing_factor, leading_factor)]

    if ctx.get("need"):
        parts.append(str(ctx["need"]))
    if ctx.get("defense_style"):
        parts.append(str(ctx["defense_style"]))
    if ctx.get("after_timeout"):
        parts.append("ATO")
    elif ctx.get("slob"):
        parts.append("SLOB")
    elif ctx.get("blob"):
        parts.append("BLOB")

    if ctx.get("_defaults_used"):
        parts.append("guardrail-defaulted")

    return " | ".join(parts)


# ---------------------------------------------------------------------
# Core builders
# ---------------------------------------------------------------------

def build_ml_matchup_table(
    season: str,
    our_team: str,
    opp_team: str,
    w_off: float = 0.7,
    w_def: float = 0.3,
    context: Optional[Dict[str, Any]] = None,
) -> pd.DataFrame:
    """
    Build the matchup table that contains BOTH:
      - Baseline prediction (PPP_BASELINE)
      - ML blend prediction (PPP_ML_BLEND)

    Advanced NLP context now influences the offense/defense blend weights.
    """
    team_df = _rec.team_df.copy()
    league_df = _rec.league_df.copy()
    ml_df = _get_ml_pred_df()

    if "PPP_ML" not in ml_df.columns:
        raise ValueError("ml_offense_ppp_predictions.csv must contain a PPP_ML column.")

    team_df = team_df.merge(
        ml_df,
        on=["SEASON", "TEAM_ABBREVIATION", "PLAY_TYPE"],
        how="left",
    )

    off = team_df.query(
        "SEASON == @season and TEAM_ABBREVIATION == @our_team and SIDE == 'offense'"
    ).copy()

    deff = team_df.query(
        "SEASON == @season and TEAM_ABBREVIATION == @opp_team and SIDE == 'defense'"
    ).copy()

    if off.empty:
        raise ValueError(f"No offensive data for {our_team} in season {season}")
    if deff.empty:
        raise ValueError(f"No defensive data for {opp_team} in season {season}")

    league_off = league_df.query(
        "SEASON == @season and SIDE == 'offense'"
    )[["PLAY_TYPE", "PPP"]].rename(columns={"PPP": "PPP_LEAGUE_OFF"})

    league_def = league_df.query(
        "SEASON == @season and SIDE == 'defense'"
    )[["PLAY_TYPE", "PPP"]].rename(columns={"PPP": "PPP_LEAGUE_DEF"})

    if league_off.empty or league_def.empty:
        raise ValueError(f"Missing league-average offense/defense data for season {season}")

    deff_subset = deff[
        [
            "PLAY_TYPE",
            "PPP",
            "POSS",
            "POSS_PCT",
            "RELIABILITY_WEIGHT",
            "EFG_PCT",
            "TOV_POSS_PCT",
        ]
    ].copy()

    merged = off.merge(
        deff_subset,
        on="PLAY_TYPE",
        suffixes=("_OFF", "_DEF"),
    )

    merged = merged.merge(league_off, on="PLAY_TYPE", how="left")
    merged = merged.merge(league_def, on="PLAY_TYPE", how="left")

    rel_off = merged["RELIABILITY_WEIGHT_OFF"].fillna(0.0)
    rel_def = merged["RELIABILITY_WEIGHT_DEF"].fillna(0.0)

    merged["PPP_OFF_SHRUNK"] = rel_off * merged["PPP_OFF"] + (1 - rel_off) * merged["PPP_LEAGUE_OFF"]
    merged["PPP_DEF_SHRUNK"] = rel_def * merged["PPP_DEF"] + (1 - rel_def) * merged["PPP_LEAGUE_DEF"]

    eff_w_off, eff_w_def = _resolve_effective_weights(context=context, w_off=w_off, w_def=w_def)

    merged["EFFECTIVE_W_OFF"] = float(eff_w_off)
    merged["EFFECTIVE_W_DEF"] = float(eff_w_def)

    merged["PPP_BASELINE"] = (
        float(eff_w_off) * merged["PPP_OFF_SHRUNK"]
        + float(eff_w_def) * (2 * merged["PPP_LEAGUE_OFF"] - merged["PPP_DEF_SHRUNK"])
    )

    merged = merged[merged["PPP_ML"].notna()].copy()
    if merged.empty:
        raise ValueError("No ML predictions available for this matchup (PPP_ML is missing).")

    merged["PPP_ML_BLEND"] = (
        float(eff_w_off) * merged["PPP_ML"]
        + float(eff_w_def) * (2 * merged["PPP_LEAGUE_OFF"] - merged["PPP_DEF_SHRUNK"])
    )

    merged["PLAY_FAMILY"] = merged["PLAY_TYPE"].apply(_play_family)
    return merged.reset_index(drop=True)


def apply_context_adjustments(
    df: pd.DataFrame,
    margin: Any,
    period: Any,
    time_remaining_period_sec: Any,
    context: Optional[Dict[str, Any]] = None,
) -> pd.DataFrame:
    """
    Apply both:
    - the legacy score/time adjustments already used in your app
    - NEW advanced NLP-aware adjustments that can materially change rank order

    Adds:
      QUICK_PRIORITY, BONUS_QUICK, BONUS_SCORE, PENALTY_PROTECT
      NEED_ADJ, DEFENSE_STYLE_ADJ, PACE_ADJ, SPECIAL_ADJ,
      FAMILY_PREF_ADJ, LATE_CLOCK_ADJ, BALL_SECURITY_PENALTY,
      LEGACY_CONTEXT_ADJ, NLP_CONTEXT_ADJ,
      CONTEXT_ADJ, PPP_CONTEXT, DELTA_VS_BASELINE,
      LATE_GAME_FACTOR, TRAILING_FACTOR, LEADING_FACTOR,
      CONTEXT_LABEL, RATIONALE

    Guardrail fields added:
      CONTEXT_DEFAULTS_USED, CONTEXT_GUARDRAILS, CONTEXT_PARSE_STATUS,
      CONTEXT_VALIDATION_OK, RATIONALE_MODE
    """
    out = df.copy()

    ctx = _normalize_context(
        margin=margin,
        period=period,
        time_remaining_period_sec=time_remaining_period_sec,
        context=context,
    )

    margin = float(ctx["margin"])
    period = int(ctx["period"])
    time_remaining_period_sec = float(ctx["time_remaining"])

    late_game_factor, trailing_factor, leading_factor = compute_context_factors(
        margin=margin,
        period=period,
        time_remaining_period_sec=time_remaining_period_sec,
    )

    urgency_mult = _context_priority_multiplier(ctx, late_game_factor, trailing_factor, leading_factor)

    out["PLAY_FAMILY"] = out["PLAY_TYPE"].apply(_play_family)

    # Make sure downstream columns exist even if source data is imperfect.
    if "EFG_PCT_OFF" not in out.columns:
        out["EFG_PCT_OFF"] = 0.0
    if "TOV_POSS_PCT_OFF" not in out.columns:
        out["TOV_POSS_PCT_OFF"] = 0.0

    out["EFG_PCT_OFF"] = pd.to_numeric(out["EFG_PCT_OFF"], errors="coerce").fillna(0.0)
    out["TOV_POSS_PCT_OFF"] = pd.to_numeric(out["TOV_POSS_PCT_OFF"], errors="coerce").fillna(0.0)

    # -----------------------------------------------------------------
    # Legacy adjustments (preserved for compatibility)
    # -----------------------------------------------------------------
    out["QUICK_PRIORITY"] = out["PLAY_TYPE"].map(QUICK_WEIGHTS).fillna(
        out["PLAY_FAMILY"].map(FAMILY_QUICK_WEIGHTS).fillna(0.0)
    )

    avg_efg = float(out["EFG_PCT_OFF"].mean()) if "EFG_PCT_OFF" in out.columns else 0.0
    avg_tov = float(out["TOV_POSS_PCT_OFF"].mean()) if "TOV_POSS_PCT_OFF" in out.columns else 0.0

    out["BONUS_QUICK"] = (
        0.04 * late_game_factor * (0.3 + trailing_factor) * out["QUICK_PRIORITY"]
    )

    out["BONUS_SCORE"] = (
        0.25
        * late_game_factor
        * trailing_factor
        * np.maximum(0.0, out["EFG_PCT_OFF"] - avg_efg)
    )

    out["PENALTY_PROTECT"] = (
        0.30
        * late_game_factor
        * leading_factor
        * np.maximum(0.0, out["TOV_POSS_PCT_OFF"] - avg_tov)
    )

    out["LEGACY_CONTEXT_ADJ"] = out["BONUS_QUICK"] + out["BONUS_SCORE"] - out["PENALTY_PROTECT"]

    # -----------------------------------------------------------------
    # Advanced NLP-aware adjustments
    # -----------------------------------------------------------------
    primary_need = ctx.get("need")
    defense_style = ctx.get("defense_style")
    pace = ctx.get("pace")
    preferred_families = set(ctx.get("preferred_play_families") or [])
    special_situations = list(ctx.get("special_situations") or [])

    def need_adj(family: str) -> float:
        base = _lookup_nested(NEED_FAMILY_BONUS, primary_need, family)
        if base == 0.0:
            return 0.0
        return float(base * urgency_mult)

    def defense_adj(family: str) -> float:
        base = _lookup_nested(DEFENSE_STYLE_FAMILY_BONUS, defense_style, family)
        if base == 0.0:
            return 0.0
        style_mult = 0.70 + 0.30 * late_game_factor
        if ctx.get("vs_switching") and family in {"cut", "post_up"}:
            style_mult += 0.10
        return float(base * style_mult)

    def pace_adj(family: str) -> float:
        base = _lookup_nested(PACE_FAMILY_BONUS, pace, family)
        if base == 0.0:
            return 0.0
        return float(base * (0.70 + 0.30 * late_game_factor))

    def special_adj(family: str) -> float:
        bonus = 0.0
        for special in special_situations:
            bonus += _lookup_nested(SPECIAL_FAMILY_BONUS, special, family)
        return float(bonus)

    def family_pref_adj(family: str) -> float:
        return _preferred_family_bonus(list(preferred_families), family)

    def late_clock_adj(family: str) -> float:
        shot_clock = _safe_float(ctx.get("shot_clock"))
        late_clock_flag = bool(ctx.get("late_clock"))
        short_clock = bool(shot_clock is not None and shot_clock <= 8)
        if not late_clock_flag and not short_clock:
            return 0.0

        base = _lookup_family_bonus(LATE_CLOCK_FAMILY_BONUS, family)
        if base == 0.0:
            return 0.0

        strength = 1.0
        if shot_clock is not None:
            strength = _clamp((8.0 - shot_clock) / 8.0 + 0.40, 0.40, 1.20)
        return float(base * strength)

    def ball_security_penalty(row: pd.Series) -> float:
        tov = float(row.get("TOV_POSS_PCT_OFF", avg_tov))
        family = str(row.get("PLAY_FAMILY", "other"))

        protect_state = bool(ctx.get("protect_lead") or ctx.get("safe"))
        if not protect_state and primary_need not in {"safe"}:
            return 0.0

        penalty = max(0.0, tov - avg_tov)
        penalty *= 0.35 * (0.60 + 0.40 * leading_factor)

        if family in RISKY_FAMILIES:
            penalty += 0.012
        if family in SECURE_FAMILIES:
            penalty -= 0.006

        return float(max(0.0, penalty))

    out["NEED_ADJ"] = out["PLAY_FAMILY"].apply(need_adj)
    out["DEFENSE_STYLE_ADJ"] = out["PLAY_FAMILY"].apply(defense_adj)
    out["PACE_ADJ"] = out["PLAY_FAMILY"].apply(pace_adj)
    out["SPECIAL_ADJ"] = out["PLAY_FAMILY"].apply(special_adj)
    out["FAMILY_PREF_ADJ"] = out["PLAY_FAMILY"].apply(family_pref_adj)
    out["LATE_CLOCK_ADJ"] = out["PLAY_FAMILY"].apply(late_clock_adj)
    out["BALL_SECURITY_PENALTY"] = out.apply(ball_security_penalty, axis=1)

    # Additional small structural nudges for mixed situations
    out["STRUCTURE_NUDGE"] = 0.0

    if defense_style == "switch":
        out.loc[out["PLAY_FAMILY"] == "post_up", "STRUCTURE_NUDGE"] += 0.010
        out.loc[out["PLAY_FAMILY"] == "cut", "STRUCTURE_NUDGE"] += 0.008

    if defense_style in {"zone_2_3", "zone_3_2", "zone_1_3_1", "generic_zone", "matchup_zone", "box_and_1"}:
        out.loc[out["PLAY_FAMILY"] == "off_screen", "STRUCTURE_NUDGE"] += 0.010
        out.loc[out["PLAY_FAMILY"] == "spot_up", "STRUCTURE_NUDGE"] += 0.008

    if primary_need == "need3":
        out.loc[out["PLAY_FAMILY"] == "post_up", "STRUCTURE_NUDGE"] -= 0.008

    if primary_need == "quick2":
        out.loc[out["PLAY_FAMILY"] == "transition", "STRUCTURE_NUDGE"] += 0.006
        out.loc[out["PLAY_FAMILY"] == "isolation", "STRUCTURE_NUDGE"] -= 0.006

    out["NLP_CONTEXT_ADJ"] = (
        out["NEED_ADJ"]
        + out["DEFENSE_STYLE_ADJ"]
        + out["PACE_ADJ"]
        + out["SPECIAL_ADJ"]
        + out["FAMILY_PREF_ADJ"]
        + out["LATE_CLOCK_ADJ"]
        + out["STRUCTURE_NUDGE"]
        - out["BALL_SECURITY_PENALTY"]
    )

    # -----------------------------------------------------------------
    # Final combination
    # -----------------------------------------------------------------
    out["CONTEXT_ADJ"] = out["LEGACY_CONTEXT_ADJ"] + out["NLP_CONTEXT_ADJ"]
    out["PPP_CONTEXT"] = out["PPP_ML_BLEND"] + out["CONTEXT_ADJ"]
    out["DELTA_VS_BASELINE"] = out["PPP_CONTEXT"] - out["PPP_BASELINE"]

    ctx_label = _make_context_label(ctx, late_game_factor, trailing_factor, leading_factor)
    out["CONTEXT_LABEL"] = ctx_label

    out["LATE_GAME_FACTOR"] = float(late_game_factor)
    out["TRAILING_FACTOR"] = float(trailing_factor)
    out["LEADING_FACTOR"] = float(leading_factor)

    out["CONTEXT_DEFAULTS_USED"] = ", ".join(ctx.get("_defaults_used", [])) if ctx.get("_defaults_used") else ""
    out["CONTEXT_GUARDRAILS"] = " | ".join(ctx.get("_guardrails", [])) if ctx.get("_guardrails") else ""
    out["CONTEXT_PARSE_STATUS"] = str(ctx.get("_parse_status", "parsed"))
    out["CONTEXT_VALIDATION_OK"] = bool(ctx.get("_validation_ok", True))
    out["RATIONALE_MODE"] = RATIONALE_MODE

    def rationale(row: pd.Series) -> str:
        parts: List[str] = []

        if float(row["NEED_ADJ"]) != 0.0 and primary_need:
            parts.append(f"need={primary_need}:{row['NEED_ADJ']:+.3f}")
        if float(row["DEFENSE_STYLE_ADJ"]) != 0.0 and defense_style:
            parts.append(f"defense={defense_style}:{row['DEFENSE_STYLE_ADJ']:+.3f}")
        if float(row["PACE_ADJ"]) != 0.0 and pace:
            parts.append(f"pace={pace}:{row['PACE_ADJ']:+.3f}")
        if float(row["SPECIAL_ADJ"]) != 0.0 and special_situations:
            parts.append(f"special:{row['SPECIAL_ADJ']:+.3f}")
        if float(row["FAMILY_PREF_ADJ"]) != 0.0:
            parts.append(f"family_match:{row['FAMILY_PREF_ADJ']:+.3f}")
        if float(row["LATE_CLOCK_ADJ"]) != 0.0:
            parts.append(f"late_clock:{row['LATE_CLOCK_ADJ']:+.3f}")
        if float(row["BALL_SECURITY_PENALTY"]) != 0.0:
            parts.append(f"ball_security:{-float(row['BALL_SECURITY_PENALTY']):+.3f}")

        detail = "; ".join(parts) if parts else "no extra NLP family adjustments"

        guardrail_note = ""
        if row["CONTEXT_PARSE_STATUS"] == "defaulted":
            guardrail_note = (
                f" Guardrail defaults used ({row['CONTEXT_DEFAULTS_USED'] or 'unspecified fields'}), "
                "so this ranking was kept in a neutral context rather than a forced late-game assumption."
            )

        return (
            f"{row['PLAY_TYPE']} [{row['PLAY_FAMILY']}]: "
            f"ML base {row['PPP_ML_BLEND']:.3f}, "
            f"legacy {row['LEGACY_CONTEXT_ADJ']:+.3f}, "
            f"NLP {row['NLP_CONTEXT_ADJ']:+.3f}, "
            f"total {row['CONTEXT_ADJ']:+.3f} ({ctx_label}). "
            f"Blend off/def={row['EFFECTIVE_W_OFF']:.2f}/{row['EFFECTIVE_W_DEF']:.2f}. "
            f"{detail}. "
            f"Late={late_game_factor:.2f}, trailing={trailing_factor:.2f}, leading={leading_factor:.2f}."
            f"{guardrail_note}"
        )

    out["RATIONALE"] = out.apply(rationale, axis=1)
    return out


def rank_ml_with_context(
    season: str,
    our_team: str,
    opp_team: str,
    margin: Any,
    period: Any,
    time_remaining_period_sec: Any,
    k: int = 5,
    w_off: float = 0.7,
    w_def: float = 0.3,
    context: Optional[Dict[str, Any]] = None,
) -> pd.DataFrame:
    """
    Full AI use case ranking:
      1) Build matchup with ML blend + baseline
      2) Let advanced NLP context alter blend weights
      3) Apply legacy + NLP-aware context adjustments
      4) Rank by PPP_CONTEXT

    Safe fallback behavior for malformed / underspecified prompts:
      - margin -> 0.0
      - period -> 4
      - time_remaining -> 360.0
    """
    sanitized_context = _normalize_context(
        margin=margin,
        period=period,
        time_remaining_period_sec=time_remaining_period_sec,
        context=context,
    )

    df = build_ml_matchup_table(
        season=season,
        our_team=our_team,
        opp_team=opp_team,
        w_off=w_off,
        w_def=w_def,
        context=sanitized_context,
    )
    df = apply_context_adjustments(
        df=df,
        margin=sanitized_context["margin"],
        period=sanitized_context["period"],
        time_remaining_period_sec=sanitized_context["time_remaining"],
        context=sanitized_context,
    )

    sort_cols = ["PPP_CONTEXT", "NLP_CONTEXT_ADJ", "PPP_ML_BLEND"]
    sort_cols = [c for c in sort_cols if c in df.columns]
    df = df.sort_values(sort_cols, ascending=False).reset_index(drop=True)
    return df.head(max(1, int(k)))


__all__ = [
    "DEFAULT_MARGIN",
    "DEFAULT_PERIOD",
    "DEFAULT_TIME_REMAINING",
    "MODULE_VERSION",
    "RATIONALE_MODE",
    "apply_context_adjustments",
    "build_ml_matchup_table",
    "compute_context_factors",
    "label_context",
    "rank_ml_with_context",
    "recommender_health",
    "sanitize_context_for_ranking",
    "total_time_remaining",
    "validate_context_guardrails",
]


if __name__ == "__main__":
    validation = validate_context_guardrails()
    print("Guardrail validation:", validation["status"], f"({validation['passed']}/{validation['total']})")

    sample_context = {
        "need": "quick2",
        "needs": ["quick2"],
        "defense_style": "switch",
        "after_timeout": True,
        "special_situations": ["after_timeout"],
        "preferred_play_families": ["ball_screen", "cut"],
        "shot_clock": 7,
        "late_clock": True,
        "offense_bias": 0.75,
        "defense_bias": 0.25,
        "parser_version": "3.0.0",
        "nlp_pipeline_version": "1.0.0",
    }

    try:
        # Normal parsed-context example
        test = rank_ml_with_context(
            season="2019-20",
            our_team="LAL",
            opp_team="BOS",
            margin=-4,
            period=4,
            time_remaining_period_sec=28,
            k=5,
            context=sample_context,
        )
        print(
            test[
                [
                    "PLAY_TYPE",
                    "PLAY_FAMILY",
                    "PPP_CONTEXT",
                    "PPP_ML_BLEND",
                    "PPP_BASELINE",
                    "NLP_CONTEXT_ADJ",
                    "LEGACY_CONTEXT_ADJ",
                    "DELTA_VS_BASELINE",
                    "CONTEXT_LABEL",
                    "CONTEXT_PARSE_STATUS",
                    "RATIONALE_MODE",
                ]
            ]
        )

        # Ambiguous prompt / fallback example
        fallback_test = rank_ml_with_context(
            season="2019-20",
            our_team="LAL",
            opp_team="BOS",
            margin=None,
            period=None,
            time_remaining_period_sec=None,
            k=3,
            context={"raw_text": "Just win the game"},
        )
        print(
            fallback_test[
                [
                    "PLAY_TYPE",
                    "PPP_CONTEXT",
                    "CONTEXT_DEFAULTS_USED",
                    "CONTEXT_PARSE_STATUS",
                    "CONTEXT_GUARDRAILS",
                ]
            ]
        )

        print("Recommender health:", recommender_health())
    except Exception as e:
        print("Smoke test failed:", e)