"""Stage a reviewed source snapshot and evidence; finalize only with supplied proof.

Uses git archive, never copies the working code tree or private environment files.
The default is staging only. No Git, Jira, model-server or deployment writes occur.
"""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import io
import json
from pathlib import Path, PurePosixPath
import re
import shutil
import subprocess
import tarfile
import zipfile


DEFAULT_OUTPUT = Path('/Users/gurkasahan/Developer/Capstone-Submission/Elaboration-Iteration-14')
REPO_URL = 'https://github.com/Basketball-Capstone-25/NBAPlayRanker'
GENERATOR = 'package_elaboration_submission.py/v1'
SOURCE_DIR = 'source/NBAPlayRanker'
EXCLUDE_PARTS = {'.git', '.vercel', '.next', '.venv', 'venv', 'node_modules',
                 '__pycache__', '.pytest_cache', '.mypy_cache', '.ruff_cache'}
RETAINED_DATA = ['backend/data/synergy_playtypes_2019_2025_players.csv',
                 'backend/data/ml_offense_ppp_predictions.csv',
                 'backend/data/pbp/shots_clean.parquet',
                 'backend/data/pbp/shots_agg.parquet',
                 'backend/data/pbp/shots_agg_league.parquet']


def git(repo, *args):
    return subprocess.check_output(['git', '-C', str(repo), *args])


def read_file(path):
    return path.read_bytes()


def excluded(name):
    path = PurePosixPath(name)
    if path.is_absolute() or '..' in path.parts:
        return 'unsafe path'
    if any(part in EXCLUDE_PARTS for part in path.parts):
        return 'dependency, deployment metadata or generated cache'
    if path.name.startswith('.env') and path.name != '.env.example':
        return 'private environment configuration'
    if path.suffix in {'.pyc', '.pyo', '.tsbuildinfo', '.zip', '.log'} or path.name == '.DS_Store':
        return 'generated bytecode, build output or local artifact'
    if name.startswith(('backend/data/pbp/cache/', 'backend/data/cache/')) or '/data/cache/' in name:
        return 'regenerable data cache; rebuild from retained clean inputs'
    if path.name == 'nba_pbp_2021_present.parquet' or 'synergy_chunks' in path.parts:
        return 'large raw/intermediate dataset; retained clean inputs are sufficient'
    return None


def scan(name, data):
    # Binary datasets/model files are not environment files; reject credential
    # structures in text without copying their values into an exception message.
    if b'\0' in data[:8192]:
        return
    text = data.decode('utf-8', errors='ignore')
    patterns = [r'eyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}',
                r'sb_(?:secret|publishable)_[A-Za-z0-9_-]{12,}',
                r'-----BEGIN [A-Z ]*PRIVATE KEY-----',
                r'"(?:access_token|refresh_token|service_role_key|secret_key)"\s*:\s*"[^"\n]{16,}"']
    if any(re.search(pattern, text) for pattern in patterns):
        raise ValueError(f'Credential-like content requires review: {name}')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--repo', type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument('--ref', default='HEAD', help='Commit/ref exported without working-tree code changes')
    parser.add_argument('--output', type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument('--finalize', action='store_true', help='Require final proof and create a ZIP')
    args = parser.parse_args()
    repo, output = args.repo.resolve(), args.output.resolve()
    if output == repo or repo in output.parents:
        raise ValueError('Submission output must be outside the source repository.')
    sha = git(repo, 'rev-parse', '--verify', args.ref + '^{commit}').decode().strip()
    status = git(repo, 'status', '--porcelain').decode()
    output.mkdir(parents=True, exist_ok=True)
    inputs_path = output / 'release-inputs.json'
    if not inputs_path.exists():
        template = {'final_ready': False, 'source_commit': None, 'frontend_deployment': None,
                    'backend_revision': 'nba-playranker-api-00005-hrn',
                    'jira_plan_risk_test_evidence': None, 'vpository_revision_evidence': None,
                    'browser_export_retest_evidence': None, 'model_file': None,
                    'reviewed_artifacts': [],
                    'note': 'Fill only with verified final values. Artifact entries use source (absolute local path) and destination (relative path under this package). Do not supply credentials.'}
        inputs_path.write_text(json.dumps(template, indent=2) + '\n')
    release = json.loads(inputs_path.read_text())
    if args.finalize:
        required = ['source_commit', 'frontend_deployment', 'backend_revision',
                    'jira_plan_risk_test_evidence', 'vpository_revision_evidence',
                    'browser_export_retest_evidence', 'model_file']
        missing = [key for key in required if not release.get(key)]
        if release.get('final_ready') is not True or missing:
            raise ValueError('Finalization blocked: final_ready is false or proof fields are missing: ' + ', '.join(missing))
        if status or release['source_commit'] != sha:
            raise ValueError('Finalization requires a clean committed checkout and matching source_commit.')

    previous_path = output / 'submission-manifest.json'
    previous = json.loads(previous_path.read_text()) if previous_path.exists() else None
    source = output / SOURCE_DIR
    if source.exists():
        if not previous or previous.get('generator') != GENERATOR:
            raise ValueError('Refusing to replace an unrecognized source folder.')
        known = {item['path']: item['sha256'] for item in previous['files']}
        for path in source.rglob('*'):
            if path.is_symlink():
                raise ValueError('Refusing to replace a staged symlink.')
            if path.is_file():
                key = path.relative_to(output).as_posix()
                if known.get(key) != hashlib.sha256(read_file(path)).hexdigest():
                    raise ValueError('Staged source was edited; preserve it before refresh: ' + key)
        shutil.rmtree(source)
    source.mkdir(parents=True)

    included, omitted = [], []
    for entry in git(repo, 'ls-tree', '-r', '-l', '-z', sha).split(b'\0'):
        if not entry:
            continue
        metadata, raw_name = entry.split(b'\t', 1)
        mode, kind, object_id, size = metadata.decode().split()
        name = raw_name.decode()
        reason = excluded(name)
        if reason:
            omitted.append({'path': name, 'reason': reason, 'bytes': int(size) if size != '-' else None})
        elif kind != 'blob' or mode not in {'100644', '100755'}:
            raise ValueError('Review non-regular tracked source before packaging: ' + name)
        elif int(size) > 50 * 1024 * 1024:
            raise ValueError('Review unexpectedly large tracked file: ' + name)
        else:
            included.append(name)
    for name in RETAINED_DATA:
        if name not in included:
            raise ValueError('Required runtime data missing from source commit: ' + name)

    archive = git(repo, 'archive', '--format=tar', sha, '--', *included)
    extracted = set()
    with tarfile.open(fileobj=io.BytesIO(archive), mode='r:') as tar:
        for member in tar.getmembers():
            if member.isdir():
                continue
            if not member.isfile() or member.name not in included:
                raise ValueError('Unexpected archive member; refusing extraction.')
            data = tar.extractfile(member).read()
            scan(member.name, data)
            destination = source / member.name
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_bytes(data)
            destination.chmod(0o755 if member.mode & 0o111 else 0o644)
            extracted.add(member.name)
    if extracted != set(included):
        raise ValueError('Git archive omitted selected files; review export-ignore attributes.')

    supplements = []
    # Stage reviewable evidence while it is still being finalized. Final mode
    # instead requires it to be committed and exported from the selected SHA.
    if not args.finalize:
        for folder in ['docs/iteration-14', 'docs/model']:
            for path in sorted((repo / folder).rglob('*')):
                if not path.is_file():
                    continue
                name = path.relative_to(repo).as_posix()
                if path.is_symlink() or excluded(name):
                    raise ValueError('Unsafe evidence supplement: ' + name)
                data = read_file(path)
                scan(name, data)
                destination = source / name
                destination.parent.mkdir(parents=True, exist_ok=True)
                destination.write_bytes(data)
                supplements.append(name)

    for item in release.get('reviewed_artifacts', []):
        destination_name = item['destination']
        relative = PurePosixPath(destination_name)
        if relative.is_absolute() or '..' in relative.parts or relative.parts[0] not in {'model', 'project-management', 'verification'}:
            raise ValueError('Artifact destination must be under model/, project-management/, or verification/.')
        original = Path(item['source'])
        if original.is_symlink() or not original.is_file() or excluded(original.name):
            raise ValueError('Invalid reviewed artifact source.')
        if original.suffix.lower() not in {'.vpp', '.pdf', '.png', '.jpg', '.csv', '.json', '.md', '.xml', '.txt'}:
            raise ValueError('Artifact type requires separate review.')
        data = read_file(original)
        scan(destination_name, data)
        if original.suffix.lower() in {'.json', '.csv', '.txt', '.md', '.xml'}:
            text = data.decode('utf-8', errors='ignore')
            if re.search(r'"(?:password|api_key|apikey)"\s*:\s*"[^"\n]+"', text):
                raise ValueError('Credential assignment in reviewed artifact requires removal: ' + destination_name)
        destination = output / destination_name
        if destination.exists() and read_file(destination) != data:
            raise ValueError('Refusing to overwrite a changed reviewed artifact: ' + destination_name)
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(data)

    model_requirement = (f"Native model and teamwork revision 51: `{release['model_file']}`; revision proof: `{release['vpository_revision_evidence']}`."
                         if args.finalize else '`model/` or the source model folder receives the final model and genuine server revision proof. Prepared design notes alone do not fulfill this.')
    source_requirement = ('The full submission ZIP includes `source/NBAPlayRanker/`, exported from the recorded Git commit, and the repository link.'
                          if args.finalize else '`source/NBAPlayRanker/` is a Git commit export. Final ZIP is withheld until evidence is complete.')
    plan_requirement = (f"Final project, risk and test snapshot: `{release['jira_plan_risk_test_evidence']}`."
                        if args.finalize else '`project-management/` or repository documentation receives final Jira snapshots/links with actual outcomes and risk comments.')
    requirements = f'''# Assignment requirements and evidence map

Source: CS Capstone Project Elaboration Iteration (2).pdf, INFO 45828, 2026,
pages 1-2. Requirements below are summarized from the supplied assignment.

| Required submission | Package location / outstanding evidence |
| --- | --- |
| Project Software Model, shared in Visual Paradigm and version controlled through VPository | {model_requirement} |
| Potentially Shippable Product Increment: full project source archive and repository link | {source_requirement} Repository: https://github.com/Basketball-Capstone-25/NBAPlayRanker. |
| Updated project, risk management and test plans | {plan_requirement} |

Software model elaboration is 20%: extend design, deployment and interaction
models for assigned stories. Genuine VPository messages must identify changes
and contributors; unclear or absent commits do not establish model work.

Implementation is 60%: implement assigned PBIs consistently with use cases,
UI requirements and design; test the system; record results in the Jira test
plan; create and schedule follow-up work for failures according to severity.

Project management is 20%: story-point estimates, development subtasks,
incremental evidence of work, truthful completed statuses, a split/future item
for incomplete scope, monitored risk comments, and newly executed test cases.

The report must clearly demonstrate each member's contribution. Dates, commits
and actual effort must remain truthful. Submission is electronic through SLATE
DropBox, not email; the portal was excluded from this integration task. The
PDF refers to SLATE for the deadline; no deadline is inferred here.
'''
    (output / 'assignment-requirements.md').write_text(requirements)
    state = 'FINAL REVIEWED PACKAGE' if args.finalize else 'STAGED — NOT THE FINAL SUBMISSION'
    readme = f'''# Basketball Playtype Ranker — Elaboration Iteration 14

INFO 45828 CS Capstone · Gurkaranjit Asahan · 3 October 2026

**{state}**

Repository: {REPO_URL}
Exported source commit: `{sha}`.

| Assigned story | Submission evidence |
| --- | --- |
| SCRUM-475 — Top-K uplift API and CSV/JSON exports | Source domain/router/tests; `source/NBAPlayRanker/docs/iteration-14/traceability.md`; live JSON/CSV parity. Descriptive, noncausal historical comparison. |
| SCRUM-476 — Predicted-versus-realized PPP calibration | Later-season holdouts, train-only preprocessing, bias/MAE/RMSE, analyst UI. Contemporaneous features limit this to retrospective analysis; SCRUM-526 tracks prospective evaluation. |
| SCRUM-481 — Gameplan Supabase storage schema | Migration, rollback SQL tests, RLS and optimistic revision contract. Browser localStorage migration remains SCRUM-482. |
| SCRUM-506 — Redeployment | Cloud Run and Vercel release evidence, actual user journeys, export regression and retest. See the dated evidence and final proof fields below. |

Read [assignment-requirements.md](assignment-requirements.md) and the
[technical evidence](source/NBAPlayRanker/docs/iteration-14/README.md).
`release-inputs.json` records final proof fields supplied by the release owner;
null fields mean pending. `submission-manifest.json` records file hashes,
source provenance, omissions and staged documentation supplements.

The source comes from Git, not an uncontrolled Desktop folder. Private `.env`
files, tokens, dependencies, `.git`, bytecode and regenerable caches are omitted.
Runtime Synergy data, precomputed PPP predictions, clean shots and aggregate
Parquet files are retained. After installing backend dependencies, regenerate
the canonical shot cache with:

```sh
cd source/NBAPlayRanker
backend/.venv/bin/python backend/data/etl/build_pbp_pipeline.py
```

Do not use `--force`: rebuilding the clean source would require the excluded raw
download. Configuration templates are included; obtain live credentials through
the authorized project owner, never through this archive.

Staging may supplement committed source with current `docs/iteration-14` and
`docs/model` evidence; every supplement is explicitly listed in the manifest.
It never substitutes uncommitted application code into the source export.
Finalization requires clean, committed source, reviewed proof and a model file.
This package does not claim a SLATE upload or substitute notes for VPository
revision history. No ZIP is created in staging mode.

To refresh after the release owner commits final source and evidence, run
`python3 scripts/package_elaboration_submission.py --ref FINAL_COMMIT` from
the canonical repository. The script refuses to replace edited staged source.
Fill the verified fields in `release-inputs.json`, including real packaged proof
paths, then set `final_ready` to true and add `--finalize` only when the owner
intends to create the final ZIP. The clean-checkout requirement prevents a final
archive from silently omitting unfinished code or evidence.
'''
    if args.finalize:
        readme = f'''# Basketball Playtype Ranker — Elaboration Iteration 14

INFO 45828 CS Capstone · Gurkaranjit Asahan · 3 October 2026

Source commit: `{sha}`. Visual Paradigm teamwork revision: **51**.
Repository: {REPO_URL}

This submission ZIP includes the project source, native software model and
updated project/risk/test evidence.

| Deliverable | File or folder |
| --- | --- |
| Complete project source | [source/NBAPlayRanker/](source/NBAPlayRanker/README.md) |
| Native Visual Paradigm model | [{Path(release['model_file']).name}](<{release['model_file']}>) |
| VPository author, comment and revision evidence | [Teamwork revision 51](<{release['vpository_revision_evidence']}>) |
| Project, risk management and test plans | [Final Jira evidence](<{release['jira_plan_risk_test_evidence']}>) |
| Implementation and verification report | [Iteration 14 evidence](source/NBAPlayRanker/docs/iteration-14/README.md) |
| Export correction retest | [Final browser evidence](<{release['browser_export_retest_evidence']}>) |

The assigned stories are SCRUM-475 (Top-K uplift API and CSV/JSON), SCRUM-476
(held-out PPP calibration), SCRUM-481 (coach-owned Gameplan storage schema), and
SCRUM-506 (redeployment). The report connects each to source commits, model
changes, development subtasks, test results and actual release identifiers.
Top-K uplift is descriptive and noncausal; calibration is retrospective because
its explanatory features include contemporaneous rates. Future forecasting is
SCRUM-526. Browser integration of the Gameplan schema remains SCRUM-482.

Frontend deployment: `{release['frontend_deployment']}` at
https://nbaplayranker-seven.vercel.app. Backend revision:
`{release['backend_revision']}`. Consult the dated verification records for
observed results and their limits.

The source is exported from Git. Credentials, `.git`, installed dependencies,
bytecode, raw downloads and regenerable caches are excluded. Required Synergy,
precomputed PPP, clean shot and aggregate files are included. After installing
dependencies using the source README, regenerate the canonical shot cache with:

```sh
cd source/NBAPlayRanker
backend/.venv/bin/python backend/data/etl/build_pbp_pipeline.py
```

Do not add `--force`; that would require the separately held raw download.
Environment templates are included without private credentials.
`submission-manifest.json` provides SHA-256 hashes, source provenance and
documented exclusions. [assignment-requirements.md](assignment-requirements.md)
maps the assignment checklist to these deliverables.

Upload this ZIP to the assignment's SLATE DropBox by the posted deadline.
This package does not claim an automated portal submission.
'''
    (output / 'README.md').write_text(readme)
    files = []
    for path in sorted(output.rglob('*')):
        if path.is_symlink():
            raise ValueError('Unexpected symlink in submission folder.')
        if path.is_file() and path.name != 'submission-manifest.json':
            name = path.relative_to(output).as_posix()
            if excluded(name):
                raise ValueError('Unexpected private/generated file in package: ' + name)
            data = read_file(path)
            scan(name, data)
            files.append({'path': name, 'bytes': len(data), 'sha256': hashlib.sha256(data).hexdigest()})
    if args.finalize:
        known = {item['path'] for item in files}
        for key in ['jira_plan_risk_test_evidence', 'vpository_revision_evidence', 'browser_export_retest_evidence', 'model_file']:
            if release[key] not in known:
                raise ValueError('Final proof must name a real packaged file: ' + key)
        if not release['model_file'].endswith('.vpp'):
            raise ValueError('Final model_file must be a real .vpp artifact.')
    manifest = {'generator': GENERATOR, 'created_at_utc': datetime.now(timezone.utc).isoformat(),
                'state': 'final' if args.finalize else 'staged', 'repository': REPO_URL,
                'source_commit': sha, 'working_tree_clean': not bool(status),
                'source_method': 'git archive of explicit reviewed tracked paths from the selected commit',
                'documentation_supplements_from_working_tree': supplements,
                'retained_runtime_data': RETAINED_DATA, 'omitted_tracked_files': omitted,
                'files': files, 'total_file_bytes_excluding_manifest': sum(item['bytes'] for item in files)}
    previous_path.write_text(json.dumps(manifest, indent=2) + '\n')
    if args.finalize:
        archive_path = output.parent / (output.name + '-' + sha[:12] + '.zip')
        with zipfile.ZipFile(archive_path, 'x', compression=zipfile.ZIP_DEFLATED) as archive:
            for path in sorted(output.rglob('*')):
                if path.is_file():
                    archive.write(path, output.name + '/' + path.relative_to(output).as_posix())
        print('Final archive: ' + str(archive_path))
    print(json.dumps({'state': manifest['state'], 'source_commit': sha, 'files': len(files) + 1,
                      'bytes_excluding_manifest': manifest['total_file_bytes_excluding_manifest'],
                      'omitted_tracked_files': len(omitted), 'output': str(output)}, indent=2))


if __name__ == '__main__':
    main()
